- name: Local Blue-Green Deployment
  hosts: localhost
  vars:
    color: "{{ lookup('env', 'COLOR') }}"
    project_path: "{{ lookup('env', 'PROJECT_PATH') }}"
    dest_base: "{{ lookup('env', 'DEPLOY_PATH') }}"
    skip_build: "{{ lookup('env', 'SKIP_BUILD') | default('false') | bool }}"

  tasks:
    - name: Find built JAR file
      find:
        paths: "{{ project_path }}/build/libs"
        patterns: "*.jar"
        recurse: no
      register: found_jars
      when: not skip_build

    - name: Fail if no JAR found
      fail:
        msg: "No JAR file found in build/libs."
      when: (not skip_build) and found_jars.matched == 0

    - name: Pick latest JAR file
      set_fact:
        source_jar: "{{ (found_jars.files | sort(attribute='mtime'))[-1].path }}"
      when: not skip_build

    - name: Ensure target folder exists
      file:
        path: "{{ dest_base }}/midterm-{{ color }}"
        state: directory
        mode: '0755'

    - name: Copy JAR to target folder
      copy:
        src: "{{ source_jar }}"
        dest: "{{ dest_base }}/midterm-{{ color }}/midterm.jar"
        mode: '0755'
      when: not skip_build

    - name: Stop current app (if running)
      shell: ps aux | grep -i midterm.jar | grep -v grep | awk {'print $2'} |xargs kill
      ignore_errors: yes

    - name: Run new version
      shell: |
        cd {{ dest_base }}/midterm-{{ color }} && nohup java -jar midterm.jar > output.log 2>&1 &
