name: CI Pipeline

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - &checkout
        name: Checkout code
        uses: actions/checkout@v4

      - &setup-java
        name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - &make-gradle-executable
        name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew bootJar

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - *checkout
      - *setup-java
      - *make-gradle-executable

      - name: Run unit tests
        run: ./gradlew test
